using ArtTechGallery.Infrastructure.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Npgsql;
using Xunit;

namespace ArtTechGallery.API.Tests;

public sealed class PostgresFixture : IAsyncLifetime
{
    private readonly string databaseName = "arttech_tests_" + Guid.NewGuid().ToString("N");
    private string adminConnection = null!;
    private readonly string storageRoot = Path.Combine(Path.GetTempPath(), "arttech-upload-tests-" + Guid.NewGuid().ToString("N"));
    public string StorageRoot => storageRoot;
    public ProfileApiFactory Factory { get; private set; } = null!;

    public async Task InitializeAsync()
    {
        adminConnection = Environment.GetEnvironmentVariable("ARTTECH_TEST_POSTGRES")
            ?? throw new InvalidOperationException(
                "Set ARTTECH_TEST_POSTGRES to a PostgreSQL admin connection for an isolated test server. " +
                "The suite creates and drops its own randomly named database; it never uses the application database.");
        await using var connection = new NpgsqlConnection(adminConnection);
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand($"CREATE DATABASE \"{databaseName}\"", connection);
        await command.ExecuteNonQueryAsync();
        var testConnection = new NpgsqlConnectionStringBuilder(adminConnection) { Database = databaseName };
        Factory = new ProfileApiFactory(testConnection.ConnectionString, storageRoot);
        await InDatabase(db => db.Database.MigrateAsync());
    }

    public async Task InDatabase(Func<AppDbContext, Task> action)
    {
        await using var scope = Factory.Services.CreateAsyncScope();
        await action(scope.ServiceProvider.GetRequiredService<AppDbContext>());
    }

    public async Task DisposeAsync()
    {
        if (Factory is not null) await Factory.DisposeAsync();
        if (adminConnection is null) return;
        NpgsqlConnection.ClearAllPools();
        await using var connection = new NpgsqlConnection(adminConnection);
        await connection.OpenAsync();
        // Only the name generated by this fixture is eligible for deletion.
        await using var command = new NpgsqlCommand($"DROP DATABASE IF EXISTS \"{databaseName}\" WITH (FORCE)", connection);
        await command.ExecuteNonQueryAsync();
        if (Directory.Exists(storageRoot)) Directory.Delete(storageRoot, true);
    }
}

public sealed class ProfileApiFactory(string connectionString, string? storageRoot = null) : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        // No Development migration/seed startup, no demo user or fixtures.
        builder.UseEnvironment("Testing");
        builder.UseSetting("ArtworkStorage:RootPath", storageRoot ?? Path.Combine(Path.GetTempPath(), "arttech-upload-tests-" + Guid.NewGuid().ToString("N")));
        builder.UseSetting("ArtworkStorage:PublicBaseUrl", "https://artwork-images.test/");
        builder.ConfigureServices(services =>
        {
            services.RemoveAll<DbContextOptions<AppDbContext>>();
            services.RemoveAll<IDbContextOptionsConfiguration<AppDbContext>>();
            services.AddDbContext<AppDbContext>(options => options.UseNpgsql(connectionString));
        });
    }
}
